version: "3.7"
services:
  app:
    build:
      args:
        user: appuser        
        uid: 1000            
      context: ./ 
      dockerfile: Dockerfile
    image: laravel-backend      
    container_name: laravel-backend  
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network        
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network        
  nginx:
    image: nginx:alpine
    container_name: nginx-container 
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./jsonplaceholder-api/public:/var/www/jsonplaceholder-api/public
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - app-network        
networks:
  app-network:            
    driver: bridge
